DROP DATABASE IF EXISTS DB_TCHAT;
CREATE DATABASE IF NOT EXISTS DB_TCHAT;
USE DB_TCHAT;

DROP TABLE IF EXISTS DB_TCHAT_MESSAGE;
CREATE TABLE IF NOT EXISTS DB_TCHAT_MESSAGE
(
	ID_MESSAGE INT AUTO_INCREMENT,
	DATE_MESSAGE DATETIME,
	MESSAGE TEXT,
	PSEUDO VARCHAR(30),
	CONSTRAINT PK_MESSAGE PRIMARY KEY (ID_MESSAGE) /*Création de la clef primaire.*/
)ENGINE = InnoDB DEFAULT CHARSET=latin1;